### ISSUE TITLE
Colab Error (RuntimeError: CUDA error: device-side assert triggered)

### ISSUE THREAD

**Issue by MaayanBogin** [abdallahdib/NextFace#12]
![image](https://user-images.githubusercontent.com/46858816/165173657-c3d5008b-d562-4191-b4ea-09609f10cd34.png)

Cant seem to find a solution to this and its getting pretty late :') 
I tried adding os.environ['CUDA_LAUNCH_BLOCKING'] = "1" but it didnt help, got any ideas? thanks a head of time :)) 

Edit: 
I added os.environ['CUDA_LAUNCH_BLOCKING'] = "1 to the classes optimizer and morphablemodel, no diff

**Comment by abdallahdib** [comment]
@MaayanBogin this is really weird, it is working on my side. can u please print the torch version and cuda version in the notebook 

print(torch.__version__)
print(torch.version.cuda)

**Comment by abdallahdib** [comment]
oh also, did u download the h5 files from the correct links 
https://faces.dmi.unibas.ch/bfm/bfm2017.html
https://github.com/waps101/AlbedoMM/releases/download/v1.0/albedoModel2020_face12_albedoPart.h5

**Comment by MaayanBogin** [comment]
Hello, Just checked and i heave the correct files from those links, here is my cuda and torch version 
1.11.0+cu113
******
11.3

Here is the error I receive
RuntimeError                              Traceback (most recent call last)
[<ipython-input-17-3f57d343b78b>](https://localhost:8080/#) in <module>()
      1 #run the optimization now
      2 os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
----> 3 optimizer.run(imagePath)
      4 #display results
      5 from IPython.display import Image, display

2 frames
[/content/NextFace/optimizer.py](https://localhost:8080/#) in run(self, imagePathOrDir, sharedIdentity, checkpoint, doStep1, doStep2, doStep3)
    423                 self.saveOutput(self.config.rtSamples, self.outputDir + '/outputStage1', prefix='stage1_')
    424         if doStep2:
--> 425             self.runStep2()
    426             if self.config.saveIntermediateStage:
    427                 self.saveOutput(self.config.rtSamples, self.outputDir + '/outputStage2', prefix='stage2_')

[/content/NextFace/optimizer.py](https://localhost:8080/#) in runStep2(self)
    228             vertices, diffAlbedo, specAlbedo = self.pipeline.morphableModel.computeShapeAlbedo(self.pipeline.vShapeCoeff, self.pipeline.vExpCoeff, self.pipeline.vAlbedoCoeff)
    229             cameraVerts = self.pipeline.camera.transformVertices(vertices, self.pipeline.vTranslation, self.pipeline.vRotation)
--> 230             diffuseTextures = self.pipeline.morphableModel.generateTextureFromAlbedo(diffAlbedo)
    231             specularTextures = self.pipeline.morphableModel.generateTextureFromAlbedo(specAlbedo)
    232 

[/content/NextFace/morphablemodel.py](https://localhost:8080/#) in generateTextureFromAlbedo(self, albedo)
    169         neighboors = torch.arange(self.faces.shape[-1], dtype = torch.int64, device = self.faces.device)
    170 
--> 171         texture = (baryCenterWeights[:, neighboors, None] * albedo[:, self.faces[oFaces[:, None], neighboors]]).sum(dim=-2)
    172         textures = torch.zeros((albedo.size(0), textureSize, textureSize, 3), dtype=torch.float32, device = self.faces.device)
    173         textures[:, uvxyMap[:, 0], uvxyMap[:, 1]] = texture

RuntimeError: CUDA error: device-side assert triggered


Thank you for your time :)

**Comment by MaayanBogin** [comment]
Sure thing!
From what it looks like, It might be a problem with torch or index error i mentioned 
https://file.io/HAVY3MSrFsAg

**Comment by MaayanBogin** [comment]
Do you have any idea how I solve this error?

**Comment by abdallahdib** [comment]
I managed to reproduce the same issue, in fact u have accidently downloaded the incorrect h5 file from basel website. because on their website there is two h5 files and u did not pick the right one. plz delete ur **morphableModel-2017.pickle** and run the library again, it will generate a new **morphableModel-2017.pickle** for u. before that ensure that u have downloaded the exact h5 files (refer to readme)

**Comment by MaayanBogin** [comment]
Ahhhhh yeah that was my bad, Seems to be working now !! Thanks very much:))
Best of luck!!
